### ISSUE TITLE
TypeError on module init (QGIS 3.28 / python 3.10 on linux)

### ISSUE THREAD

**Issue by vidlb** [MathieuChailloux/BioDispersal#24]
J'ai un bug lorsque initialise le plugin :
```raw
TypeError: 'type' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/vidlb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BioDispersal/BioDispersal.py", line 196, in initGui
    self.dlg.initTabs()
  File "/home/vidlb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BioDispersal/BioDispersal_dialog.py", line 87, in initTabs
    self.bdModel = BioDispersalModel(self.context,self.feedback)
  File "/home/vidlb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BioDispersal/BioDispersal_model.py", line 37, in __init__
    self.stModel = subnetworks.STModel(self)
  File "/home/vidlb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BioDispersal/steps/subnetworks.py", line 98, in __init__
    super().__init__(self,itemClass,feedback=bdModel.feedback)
  File "/home/vidlb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/BioDispersal/qgis_lib_mc/abstract_model.py", line 599, in __init__
    if fieldname in self.fields:
TypeError: 'type' object is not subscriptable
```

J'ai trouvé le soucis, c'est une mauvaise utilisation de la fonction super(), je vais te proposer une MR

**Comment by vidlb** [comment]
Ha ouais je viens de voir que j'avais ce bug parce que je suis reparti de ta branche master de qgis_lib_mc.  
Bref l'issue est dans le mauvais github, mais bon. J'avais pas vu que tu faisai ref à un commit précis de qgis_lib_mc, et pas directement la branche master.  

En tous cas normalement tout fonctionne avec mes 2 MR !

**Comment by vidlb** [comment]
Bon je viens de réaliser que c'est la galère vu que je suis reparti de ta branche master qui visiblement était bien en avance sur le commit fonctionnel dont tu te sers dans BioDispersal...quelle galère, je comprends l'idée de mutualiser des fonctions dans qgis_lib_mc mais c'est une horreur à debuf

**Comment by vidlb** [comment]
P.S. : 
Je te conseille quand meme de regarder les modifs que j'avais suggéré dans https://github.com/MathieuChailloux/BioDispersal/pull/25/files ; il ne faut pas repasser `self` à `super().__init__`
